name: Test Docker Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Test Docker Compose Build
      run: |
        docker compose build
        
    - name: Test Docker Compose Up
      run: |
        docker compose up -d
        sleep 30
        docker compose ps
        docker compose logs
        docker compose down 